// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107005940_SeedCamisetas")]
    partial class SeedCamisetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Clube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LigaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LigaId");

                    b.ToTable("Clubes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LigaId = 1,
                            Nome = "Flamengo"
                        },
                        new
                        {
                            Id = 2,
                            LigaId = 1,
                            Nome = "Palmeiras"
                        },
                        new
                        {
                            Id = 3,
                            LigaId = 2,
                            Nome = "Real Madrid"
                        },
                        new
                        {
                            Id = 4,
                            LigaId = 2,
                            Nome = "Manchester City"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ligas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Campeonato Brasileiro"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Champions League"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubeId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubeId = 1,
                            Descricao = "Camisa oficial do Flamengo - modelo 2025",
                            ImagemUrl = "/imagens/flamengo.jpg",
                            Nome = "Camisa Flamengo 2025",
                            Preco = 349.90m
                        },
                        new
                        {
                            Id = 2,
                            ClubeId = 2,
                            Descricao = "Camisa oficial do Palmeiras - modelo 2025",
                            ImagemUrl = "/imagens/palmeiras.jpg",
                            Nome = "Camisa Palmeiras 2025",
                            Preco = 339.90m
                        },
new
                        {
                            Id = 5,
                            ClubeId = 5,
                            CampeonatoId = 1,
                            Nome = "Camisa Atlético MG 2025",
                            Descricao = "Camisa oficial do Atlético Mineiro 2025, conforto e estilo garantidos",
                            ImagemUrl = "/imagens/clubes/atleticomg1.jpg",
                            Preco = 329.90m
                        },
                        new
                        {
                            Id = 6,
                            ClubeId = 6,
                            CampeonatoId = 1,
                            Nome = "Camisa São Paulo 2025",
                            Descricao = "Camisa oficial do São Paulo 2025, feita para torcedores apaixonados",
                            ImagemUrl = "/imagens/clubes/saopaulo1.jpg",
                            Preco = 319.90m
                        },
                        new
                        {
                            Id = 7,
                            ClubeId = 7,
                            CampeonatoId = 1,
                            Nome = "Camisa Corinthians 2025",
                            Descricao = "Camisa oficial do Corinthians, modelo 2025, com tecido respirável",
                            ImagemUrl = "/imagens/clubes/corinthians1.jpg",
                            Preco = 329.90m
                        },
                        new
                        {
                            Id = 8,
                            ClubeId = 8,
                            CampeonatoId = 1,
                            Nome = "Camisa Athletico PR 2025",
                            Descricao = "Camisa oficial do Athletico Paranaense, modelo 2025, tecido respirável",
                            ImagemUrl = "/imagens/clubes/athleticopr1.jpg",
                            Preco = 319.90m
                        },
                        new
                        {
                            Id = 9,
                            ClubeId = 9,
                            CampeonatoId = 1,
                            Nome = "Camisa Ceará 2025",
                            Descricao = "Camisa oficial do Ceará 2025, design moderno e confortável",
                            ImagemUrl = "/imagens/clubes/ceara1.jpg",
                            Preco = 299.90m
                        },
                        new
                        {
                            Id = 10,
                            ClubeId = 10,
                            CampeonatoId = 1,
                            Nome = "Camisa Fortaleza 2025",
                            Descricao = "Camisa oficial do Fortaleza 2025, perfeita para torcer na arquibancada",
                            ImagemUrl = "/imagens/clubes/fortaleza1.jpg",
                            Preco = 299.90m
                        },
                        new
                        {
                            Id = 11,
                            ClubeId = 11,
                            CampeonatoId = 1,
                            Nome = "Camisa Bahia 2025",
                            Descricao = "Camisa oficial do Bahia 2025, confortável e estilosa",
                            ImagemUrl = "/imagens/clubes/bahia1.jpg",
                            Preco = 299.90m
                        },
                        new
                        {
                            Id = 12,
                            ClubeId = 12,
                            CampeonatoId = 1,
                            Nome = "Camisa Coritiba 2025",
                            Descricao = "Camisa oficial do Coritiba 2025, design moderno e leve",
                            ImagemUrl = "/imagens/clubes/coritiba1.jpg",
                            Preco = 289.90m
                        },
                        new
                        {
                            Id = 13,
                            ClubeId = 13,
                            CampeonatoId = 1,
                            Nome = "Camisa América MG 2025",
                            Descricao = "Camisa oficial do América Mineiro 2025, conforto e estilo",
                            ImagemUrl = "/imagens/clubes/americamg1.jpg",
                            Preco = 289.90m
                        },
                        new
                        {
                            Id = 14,
                            ClubeId = 14,
                            CampeonatoId = 1,
                            Nome = "Camisa Goiás 2025",
                            Descricao = "Camisa oficial do Goiás 2025, perfeita para torcedores",
                            ImagemUrl = "/imagens/clubes/goias1.jpg",
                            Preco = 279.90m
                        },
                        new
                        {
                            Id = 15,
                            ClubeId = 15,
                            CampeonatoId = 1,
                            Nome = "Camisa Botafogo 2025",
                            Descricao = "Camisa oficial do Botafogo 2025, design clássico e confortável",
                            ImagemUrl = "/imagens/clubes/botafogo1.jpg",
                            Preco = 319.90m
                        },
                        new
                        {
                            Id = 16,
                            ClubeId = 16,
                            CampeonatoId = 1,
                            Nome = "Camisa Atlético GO 2025",
                            Descricao = "Camisa oficial do Atlético Goianiense 2025, moderna e leve",
                            ImagemUrl = "/imagens/clubes/atleticogo1.jpg",
                            Preco = 289.90m
                        },
                        new
                        {
                            Id = 17,
                            ClubeId = 17,
                            CampeonatoId = 1,
                            Nome = "Camisa Juventude 2025",
                            Descricao = "Camisa oficial do Juventude 2025, confortável e estilosa",
                            ImagemUrl = "/imagens/clubes/juventude1.jpg",
                            Preco = 279.90m
                        },
                        new
                        {
                            Id = 18,
                            ClubeId = 18,
                            CampeonatoId = 1,
                            Nome = "Camisa Vasco 2025",
                            Descricao = "Camisa oficial do Vasco 2025, clássica e resistente",
                            ImagemUrl = "/imagens/clubes/vasco1.jpg",
                            Preco = 309.90m
                        },
                        new
                        {
                            Id = 19,
                            ClubeId = 19,
                            CampeonatoId = 1,
                            Nome = "Camisa Grêmio 2025",
                            Descricao = "Camisa oficial do Grêmio 2025, confortável e moderna",
                            ImagemUrl = "/imagens/clubes/gremio1.jpg",
                            Preco = 309.90m
                        },
                        new
                        {
                            Id = 20,
                            ClubeId = 20,
                            CampeonatoId = 1,
                            Nome = "Camisa São Bento 2025",
                            Descricao = "Camisa oficial do São Bento 2025, leve e resistente",
                            ImagemUrl = "/imagens/clubes/saobento1.jpg",
                            Preco = 279.90m
                        },
                        new
                        {   
                            Id = 21,
                            ClubeId = 21,
                            CampeonatoId = 1,
                            Nome = "Camisa Internacional 2025",
                            Descricao = "Camisa oficial do Internacional, modelo 2025, confortável e resistente",
                            ImagemUrl = "/imagens/clubes/internacional1.jpg",
                            Preco = 319.90m
                        },
                        new
                        {
                        Id = 22,
                        ClubeId = 2,
                        CampeonatoId = 1,
                        Nome = "Camisa Santos 2025",
                        Descricao = "Camisa oficial do Santos, modelo 2025, perfeita para torcer em grande estilo",
                        ImagemUrl = "/imagens/clubes/santos1.jpg",
                        Preco = 309.90m
                        },
                        new
                        {
                            Id = 3,
                            ClubeId = 3,
                            Descricao = "Camisa oficial do Real Madrid - modelo 2025",
                            ImagemUrl = "/imagens/realmadrid.jpg",
                            Nome = "Camisa Real Madrid 2025",
                            Preco = 399.90m
                        },
                        new
                        {
                            Id = 4,
                            ClubeId = 4,
                            Descricao = "Camisa oficial do Manchester City - modelo 2025",
                            ImagemUrl = "/imagens/mancity.jpg",
                            Nome = "Camisa Manchester City 2025",
                            Preco = 379.90m
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Clube", b =>
                {
                    b.HasOne("WebApplication1.Models.Liga", "Liga")
                        .WithMany("Clubes")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("WebApplication1.Models.Produto", b =>
                {
                    b.HasOne("WebApplication1.Models.Clube", "Clube")
                        .WithMany("Produtos")
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");
                });

            modelBuilder.Entity("WebApplication1.Models.Clube", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("WebApplication1.Models.Liga", b =>
                {
                    b.Navigation("Clubes");
                });
#pragma warning restore 612, 618
        }
    }
}
